name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome!!! and Thank-you, for your contribution, we will check it out soon."
        pr-message: "Hey This is your first PR here. Thanks for your valuable contribution. Have a great day ahead."
